### PR TITLE
updatees

### PR DESCRIPTION
**Pull request by IThundxr**

### CODE REVIEW

**Comment by IThundxr** [comment]
Adds some serverside performance mods and makes it easy to export serverside mods

**Comment by IThundxr** [comment]
canary and radium reforged conflict

**Comment by IThundxr** [comment]
Add like advanced preipherals

**Comment by IThundxr** [comment]
Remove cc bridge 

L moment 🤣

**Comment by IThundxr** [comment]
Simple voice chat, simple shops, ae2 or rs with addons

**Comment by IThundxr** [comment]
Nuke tis3d

**Comment by IThundxr** [comment]
Ae2 texture pack for create like stuff

**Comment by UnitingMatrixXCV** [comment]
[ComputerCreate Resource Pack](https://www.curseforge.com/minecraft/texture-packs/computercreate)

**Comment by IThundxr** [comment]
Ban inf chocobars perm and add delete item mod

**Comment by IThundxr** [comment]
Hexcasting

**Comment by UnitingMatrixXCV** [comment]
[More Red](https://www.curseforge.com/minecraft/mc-mods/more-red)

**Comment by UnitingMatrixXCV** [comment]
[In Control!](https://www.curseforge.com/minecraft/mc-mods/in-control)
remove bat spawning
prevent endermen from despawning if holding a block

**Comment by UnitingMatrixXCV** [comment]
[Carry On](https://www.curseforge.com/minecraft/mc-mods/carry-on)

**Comment by IThundxr** [comment]
Update bark tags in kubejs since hexcasting was removed

**Pull request merged**
