### PR TITLE
Update again

### PR DESCRIPTION
**Pull request by IThundxr**

### CODE REVIEW

**Comment by IThundxr** [comment]
Remove immersive weathering

**Comment by IThundxr** [comment]
Etched

**Comment by IThundxr** [comment]
Ferritecore and optimizations

**Comment by IThundxr** [comment]
Fix cc screen light bug and workout radon and starlight

**Comment by Odgug** [comment]
add modernfix

**Review by SpottyTheTurtle — APPROVED** [review]
all looks good

**Pull request merged**
